### ISSUE TITLE
Spark installation failure

### ISSUE THREAD

**Issue by vchalmel** [michaelchanwahyan/datalab#27]
I'm trying to update an old fork of your datalab and checked your new version,

I get a failure on pyspark installation :
RuntimeError: Spark distribution of 3.2 is not supported. Hadoop version should be one of [hadoop2, hadoop3, without-hadoop]

Any thought ?

**Comment by vchalmel** [comment]
Full trace
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l2hvm03d/pyspark_c9b06300bf5e4288825336d80ac00208/setup.py", line 199, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-l2hvm03d/pyspark_c9b06300bf5e4288825336d80ac00208/setup.py", line 132, in run
          spark_version, hadoop_version, hive_version = install_module.checked_versions(
        File "pyspark/install.py", line 75, in checked_versions
          raise RuntimeError(
      RuntimeError: Spark distribution of 3.2 is not supported. Hadoop version should be one of [hadoop2, hadoop3, without-hadoop]
```

**Comment by vchalmel** [comment]
Things I think might be related in Dockerfile :

- folders for hadoop 2.7 not 3.2 in path
- environment variables for hadoop 3.2 defined but lines to actually install hadoop 3.2 are commented

**Comment by vchalmel** [comment]
Managed to get everything up and running by fixing the elements listed in previous post, my guess would be that the main improvement is setting :

RUN PYSPARK_HADOOP_VERSION=3.2 pip3 install pyspark==3.2.0

**Comment by michaelchanwahyan** [comment]
thanks @vchalmel for your feedback.     ya indeed I overlook these important things.
I'm creating a branch to work on the fixing.

and will also consider @arjun289's suggestion to make pyspark to a stable release version

thx
